
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model, with a test designed to fail"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model, illustrating DAG structure"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
